name: Generate GitHub Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-graph:
    name: Generate Activity Graph
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Activity Graph
        uses: lowlighter/metrics@latest
        with:
          filename: activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add activity-graph.svg
          git commit -m "Updated Activity Graph" || echo "No changes to commit"
          git push
